### ISSUE TITLE
Mem alloc error over RC7

### ISSUE THREAD

**Issue by sashakolpakov** [rgugliel/AlVin#9]
Issuing `./alvin -k=rc7 -qf [-1,0,0],1,1,1,1` works out a Coxeter polytope.

However, issuing `./alvin -k=rc7 -qf [-1,0,0],2,1,1,1` gives an error:

` *** Error in ./alvin: malloc(): memory corruption (fast): 0xab05cca0 *** `
`Aborted`

This one is compiled under linux (not macOS), and under ARM, not x86 (same libraries as supplied with AlVin compile and build fine. A new version of GAOL is necessary to build under ARM, and '-msse3' flag has to be removed for ARM's make, as this is an x86 flag -- this is to say, I would not think that the problem lies with the other architecture)

**Comment by sashakolpakov** [comment]
Same issue with `./alvin -k=rc7 -qf [-1,0,1],1,1,1,1`

**Comment by rgugliel** [comment]
Can you indicate the number of vectors after which AlVin crashes or, even better, the output (for the form [-1,0,0],2,1,1,1)

Thanks

**Comment by sashakolpakov** [comment]
The error message above is the only output I get.

**Comment by rgugliel** [comment]
Then in that case I cannot reproduce nor investigate (on my computer, AlVin runs and find more then 30 vectors).

**Comment by sashakolpakov** [comment]
Ok, I will try to look more into it. May be one of the libraries is a source of trouble: however, I followed the usual installation instructions.

**Comment by rgugliel** [comment]
Yes. mac and arm are not really tested. You can also use a VM if needed.
